replicaCount: 3

image:
  repository: ghcr.io/wangzhonghua1984/newrelic-manager
  tag: 106f79b5450b459421262f17aa6c93ffc5c7c7f1
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

namespace: newrelic-infra-manager

persistence:
  claimName: infra-manager-data
  mountPath: /app/data
  accessMode: ReadWriteOnce
  size: 1Gi

service:
  name: newrelic-infra-manager-svc
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  className: traefik
  host: infra-manager.jeffstan.cloud
  path: /
  pathType: Prefix

strategy:
  type: RollingUpdate
  maxSurge: 25%
  maxUnavailable: 25%

revisionHistoryLimit: 10
