replicaCount: 3

image:
  repository: ghcr.io/wangzhonghua1984/newrelic-manager
  tag: 2cfbc24fefa6f6b2c71b65d5351a1d1916431c56
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

namespace: newrelic-infra-manager

persistence:
  claimName: infra-manager-data
  mountPath: /app/data
  accessMode: ReadWriteOnce
  size: 1Gi

service:
  name: newrelic-infra-manager-svc
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  className: traefik
  host: infra-manager.jeffstan.cloud
  path: /
  pathType: Prefix

strategy:
  type: RollingUpdate
  maxSurge: 25%
  maxUnavailable: 25%

revisionHistoryLimit: 10

redis:
  enabled: true
  persistence:
    size: 1Gi

celery:
  enabled: true
  queues: "batch,install,default"
  logLevel: info
